stages:
  - test
  - build
  - staging
  - deploy

variables:
  PACKAGE: sps-FIXME
  UCS_VERSION: "448"
  UCS_RELEASE: "4.4"
  BRANCH: "4.4"
  SCOPE: "sps"
  LANG: "C.UTF-8"
  DEBIAN_FRONTEND: noninteractive
  CI_REGISTRY: docker-registry.knut.univention.de
  IMAGE_UCSDEV: $CI_REGISTRY/phahn/ucs-devbase:$UCS_VERSION
  IMAGE_UCSLINT: $CI_REGISTRY/ucslint:$UCS_VERSION
  IMAGE_SSH: $CI_REGISTRY/knut/ssh
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"
  IMPORT_HOST: "omar.knut.univention.de"
  BUILD_HOST: "dimma.knut.univention.de"

run_ucslint:
  stage: test
  image:
    name: $IMAGE_UCSLINT
    entrypoint: [""]
  script:
    - ucslint -j ucslint.xml -x 20
  artifacts:
    reports:
      junit: ucslint.xml

build_package:
  stage: build
  image: $IMAGE_UCSDEV
  before_script:
    - apt-get -q --assume-yes build-dep .
  script:
    - dpkg-buildpackage
    - mkdir -p _build/
    - mv ../*.tar.gz ../*.dsc ../*.deb ../*.buildinfo ../*.changes _build/
  artifacts:
    paths:
      - _build/

repo_admin:
  stage: staging
  variables:
    GIT_STRATEGY: none  # disables `git clone` altogether
  image:
    name: $IMAGE_SSH
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - debian/changelog
  before_script:
    - chmod 0600 "$SSH_PRIVATE_KEY"
    - md5sum $SSH_PRIVATE_KEY
  script:
    - |
      set -x && ssh -i "$SSH_PRIVATE_KEY" \
        -o BatchMode=yes \
        -l build \
        $IMPORT_HOST \
        repo_admin.py \
          -G $CI_REPOSITORY_URL \
          -p $PACKAGE \
          -b $BRANCH \
          -P . \
          -s $SCOPE \
          -r ${UCS_RELEASE}-0-0

build-package-ng:
  stage: deploy
  needs:
    - job: repo_admin
      artifacts: false
  variables:
    GIT_STRATEGY: none  # disables `git clone` altogether
  image:
    name: $IMAGE_SSH
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - debian/changelog
  before_script:
    - chmod 0600 "$SSH_PRIVATE_KEY"
    - md5sum $SSH_PRIVATE_KEY
  script:
    - |
      set -x && ssh -i "$SSH_PRIVATE_KEY" \
        -o BatchMode=yes \
        -l build \
        $BUILD_HOST \
        build-package-ng \
          --no-pbuilder-update \
          -P ucs \
          -p $PACKAGE \
          -s $SCOPE \
          -r ${UCS_RELEASE}-0-0


# vim: filetype=yaml expandtab tabstop=2 shiftwidth=2 softtabstop=2
