#!/bin/sh
# postinst script for sps-portal
#
# see: dh_installdeb(1)
#
# Copyright (C) 2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of the software contained in this package
# as well as the source package itself are made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this package provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use the software under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.


#DEBHELPER#
base="$(/usr/sbin/ucr get ldap/base)"

/usr/sbin/udm portals/portal remove --ignore_not_exists --dn "cn=local,cn=portal,cn=portals,cn=univention,$base"
/usr/sbin/udm portals/category remove --ignore_not_exists --dn "cn=local-admin,cn=category,cn=portals,cn=univention,$base"
/usr/sbin/udm portals/category remove --ignore_not_exists --dn "cn=local-service,cn=category,cn=portals,cn=univention,$base"
/usr/sbin/udm portals/entry remove --ignore_not_exists --dn "cn=ucs-local-to-domain,cn=entry,cn=portals,cn=univention,$base"
/usr/sbin/udm portals/entry remove --ignore_not_exists --dn "cn=umc-local,cn=entry,cn=portals,cn=univention,$base"

/usr/sbin/udm portals/entry remove --ignore_not_exists --dn "cn=univentionblog,cn=entry,cn=portals,cn=univention,$base"
/usr/sbin/udm portals/entry remove --ignore_not_exists --dn "cn=ox_app_suite_login,cn=entry,cn=portals,cn=univention,$base"
/usr/sbin/udm portals/entry remove --ignore_not_exists --dn "cn=nextcloud,cn=entry,cn=portals,cn=univention,$base"

encode () {
	base64 "$1" | tr -d '\n'
}

tempfile=$(mktemp)
cat <<__EOT >"$tempfile"
dn: cn=domain,cn=portal,cn=portals,cn=univention,$base
changetype: modify
replace: univentionNewPortalBackground
univentionNewPortalBackground: $(encode /usr/share/univention-sps/background.png)
__EOT

ldapmodify -x -D "cn=admin,$base" -y /etc/ldap.secret -f "$tempfile"

/usr/sbin/udm portals/entry modify --dn "cn=umc-domain,cn=entry,cn=portals,cn=univention,$base" \
	--set icon="$(encode /usr/share/univention-sps/icons/udm.png)"

/usr/sbin/udm portals/entry create --ignore_exists \
	--position "cn=entry,cn=portals,cn=univention,$base" \
	--set name="mail" \
	--set link="/appsuite/#!!&app=io.ox/mail" \
	--append description="de_DE Mail" \
	--append description="en_US Mail" \
	--append displayName="de_DE Mail" \
	--append displayName="en_US Mail" \
	--set icon="$(encode /usr/share/univention-sps/icons/mail.png)"

/usr/sbin/udm portals/entry create --ignore_exists \
	--position "cn=entry,cn=portals,cn=univention,$base" \
	--set name="addressbook" \
	--set link="/appsuite/#!!&app=io.ox/contacts" \
	--append description='de_DE "Zugriff auf das persönliche Adressbuch"' \
	--append description="en_US Contacts" \
	--append displayName="de_DE Adressbuch" \
	--append displayName='en_US "Address Book"' \
	--set icon="$(encode /usr/share/univention-sps/icons/address-book.png)"

/usr/sbin/udm portals/entry create --ignore_exists \
	--position "cn=entry,cn=portals,cn=univention,$base" \
	--set name="calendar" \
	--set link="/appsuite/#!!&app=io.ox/calendar" \
	--append description='de_DE "Zugriff auf den persönlichen Kalender"' \
	--append description="en_US Calendar" \
	--append displayName="de_DE Kalender" \
	--append displayName="en_US Calendar" \
	--set icon="$(encode /usr/share/univention-sps/icons/calendar.png)"

/usr/sbin/udm portals/entry create --ignore_exists \
	--position "cn=entry,cn=portals,cn=univention,$base" \
	--set name="talk" \
	--set link="/nextcloud/apps/spreed/" \
	--append description='de_DE "Zugang zu Videokonferenzen und Chat"' \
	--append description='en_US "Video Conferencing and Chat"' \
	--append displayName="de_DE Talk" \
	--append displayName="en_US Talk" \
	--set icon="$(encode /usr/share/univention-sps/icons/talk.png)"

/usr/sbin/udm portals/entry create --ignore_exists \
	--position "cn=entry,cn=portals,cn=univention,$base" \
	--set name="files" \
	--set link="/nextcloud/apps/files/" \
	--append description='de_DE "Zugriff auf die Dateisynchronisation und freigabe"' \
	--append description='en_US "File Share and Synchronisation"' \
	--append displayName="de_DE Dateien" \
	--append displayName="en_US Files" \
	--set icon="$(encode /usr/share/univention-sps/icons/files.png)"

/usr/sbin/udm portals/category modify --dn "cn=domain-service,cn=category,cn=portals,cn=univention,$base" \
	--append entries="cn=mail,cn=entry,cn=portals,cn=univention,$base" \
	--append entries="cn=addressbook,cn=entry,cn=portals,cn=univention,$base" \
	--append entries="cn=calendar,cn=entry,cn=portals,cn=univention,$base" \
	--append entries="cn=talk,cn=entry,cn=portals,cn=univention,$base" \
	--append entries="cn=files,cn=entry,cn=portals,cn=univention,$base"

/usr/sbin/udm portals/portal modify --dn "cn=domain,cn=portal,cn=portals,cn=univention,$base" \
	--remove categories

/usr/sbin/udm portals/portal modify --dn "cn=domain,cn=portal,cn=portals,cn=univention,$base" \
	--append categories="cn=domain-service,cn=category,cn=portals,cn=univention,$base" \
	--append categories="cn=domain-admin,cn=category,cn=portals,cn=univention,$base"

systemctl restart univention-portal-server

exit 0
