#!/bin/sh
# postinst script for sps-branding
#
# see: dh_installdeb(1)
#
# Copyright (C) 2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of the software contained in this package
# as well as the source package itself are made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this package provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use the software under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.


#DEBHELPER#

# Nextcloud

/usr/bin/univention-app shell nextcloud sudo -u www-data php /var/www/html/occ theming:config color "#666666"
nextcloud_docker_id=$(docker ps -a | grep 'nextcloud' -m 1 | awk '{ print $1 }')
docker cp /usr/share/univention-sps/SPS_Logo.png "$nextcloud_docker_id":/var/www/html/themes/
/usr/bin/univention-app shell nextcloud sudo -u www-data php /var/www/html/occ theming:config logo "/var/www/html/themes/SPS_Logo.png"

# Open-Xchange

cp /usr/share/univention-sps/SPS_Logo.png /var/www/appsuite/
echo "Setting OX maincolor..."
/usr/sbin/univention-config-registry set ox/cfg/settings/open-xchange-dynamic-theme.properties/io.ox/dynamic-theme//mainColor=#666666
echo "Setting OX topbarbackground..."
/usr/sbin/univention-config-registry set ox/cfg/settings/open-xchange-dynamic-theme.properties/io.ox/dynamic-theme//topbarBackground=#666666
echo "Setting OX logo..."
/usr/sbin/univention-config-registry set ox/cfg/settings/open-xchange-dynamic-theme.properties/io.ox/dynamic-theme//logoWidth=48
/usr/sbin/univention-config-registry set ox/cfg/settings/open-xchange-dynamic-theme.properties/io.ox/dynamic-theme//logoHeight=Auto
/usr/sbin/univention-config-registry set ox/cfg/settings/open-xchange-dynamic-theme.properties/io.ox/dynamic-theme//logoURL=SPS_Logo.png
echo "com.openexchange.capability.dynamic-theme=true" >> /opt/open-xchange/etc/settings/open-xchange-dynamic-theme.properties

# restart all services affected by changes
echo "Restarting services..."
/usr/bin/univention-app restart nextcloud
/usr/bin/univention-app restart oxseforucs
service univention-portal-server restart

exit 0
